// styles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 50,
        backgroundColor: '#000',
        borderBottomWidth: 1,
        borderBottomColor: '#6b4324',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    headerSubtitle: {
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        color: '#9f795c',
        marginTop: 2,
    },
    headerActions: {
        flexDirection: 'row',
        gap: 10,
    },
    addButton: {
        backgroundColor: '#6b4324',
        borderRadius: 25,
        padding: 10,
    },
    content: {
        flex: 1,
        padding: 15,
    },
    clienteCard: {
        backgroundColor: '#000',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    clienteHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    clienteInfo: {
        flex: 1,
    },
    clienteNumero: {
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    clienteCliente: {
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        color: '#9f795c',
        marginTop: 2,
    },
    clienteTempo: {
        fontSize: 12,
        fontFamily: 'Inter-SemiBold',
        color: '#6b4324',
        marginTop: 2,
        fontWeight: '600',
    },
    pedidoCard: {
        backgroundColor: '#000',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    pedidoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    pedidoInfo: {
        flex: 1,
    },
    pedidoNumero: {
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    pedidoCliente: {
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        color: '#9f795c',
        marginTop: 2,
    },
    pedidoTempo: {
        fontSize: 12,
        fontFamily: 'Inter-SemiBold',
        color: '#6b4324',
        marginTop: 2,
        fontWeight: '600',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 20,
        gap: 5,
    },
    statusText: {
        color: '#e6e6e6',
        fontSize: 12,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
    },
    pedidoItens: {
        marginBottom: 10,
    },
    itemText: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        marginBottom: 3,
    },
    pedidoFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#6b4324',
    },
    pedidoTotal: {
        color: '#e6e6e6',
        fontSize: 16,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
    },
    statusButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    statusButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        gap: 4,
        backgroundColor: '#51CE70'
    },
    statusButtonText: {
        color: '#e6e6e6',
        fontSize: 12,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 50,
    },
    emptyStateText: {
        color: '#9f795c',
        fontSize: 16,
        fontFamily: 'Inter-Regular',
        textAlign: 'center',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#000',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 50,
        backgroundColor: '#000',
        borderBottomWidth: 1,
        borderBottomColor: '#6b4324',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    clienteInput: {
        backgroundColor: '#000',
        color: '#e6e6e6',
        padding: 15,
        margin: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
        fontFamily: 'Inter-Regular',
    },
    clientesList: {
        flex: 1,
        padding: 15,
    },
    clienteItem: {
        backgroundColor: '#000',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        marginBottom: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    produtosList: {
        flex: 1,
        padding: 15,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    produtoItem: {
        backgroundColor: '#000',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        marginBottom: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    produtoNome: {
        color: '#e6e6e6',
        fontSize: 16,
        fontFamily: 'Inter-Medium',
        flex: 1,
    },
    produtoPreco: {
        color: '#6b4324',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
    },
    pedidoResumo: {
        backgroundColor: '#000',
        padding: 15,
        borderTopWidth: 1,
        borderTopColor: '#6b4324',
    },
    itemResumo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    itemResumoText: {
        color: '#9f795c',
        fontFamily: 'Inter-Regular',
        flex: 1,
    },
    totalContainer: {
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: '#6b4324',
        marginTop: 10,
    },
    totalText: {
        color: '#e6e6e6',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        textAlign: 'center',
    },
    finalizarButton: {
        backgroundColor: '#10B981',
        padding: 15,
        borderRadius: 8,
        marginTop: 15,
        alignItems: 'center',
    },
    finalizarButtonText: {
        color: '#e6e6e6',
        fontSize: 16,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        },
    alertContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F97316',
        padding: 12,
        margin: 15,
        borderRadius: 8,
        gap: 8,
    },
    alertText: {
        color: '#fff',
        fontWeight: '600',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        margin: 15,
        paddingHorizontal: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    searchInput: {
        flex: 1,
        color: '#e6e6e6',
        padding: 15,
        fontSize: 16,
        fontFamily: 'Inter-Regular',
    },
    produtoCard: {
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#333',
    },
    clienteHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    clienteInfo: {
        flex: 1,
    },
    clienteNome: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    clienteCategoria: {
        fontSize: 14,
        color: '#888',
        marginTop: 2,
    },
    clienteNumero: {
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        color: '#e6e6e6',
    },
    clienteCliente: {
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        color: '#9f795c',
        marginTop: 2,
    },
    clienteTempo: {
        fontSize: 12,
        fontFamily: 'Inter-SemiBold',
        color: '#6b4324',
        marginTop: 2,
        fontWeight: '600',
    },
    produtoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    produtoInfo: {
        flex: 1,
    },
    produtoNome: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    produtoCategoria: {
        fontSize: 14,
        color: '#888',
        marginTop: 2,
    },
    produtoActions: {
        flexDirection: 'row',
        gap: 8,
    },
    actionButton: {
        padding: 8,
    },
    produtoDetalhes: {
        gap: 8,
    },
    detalheItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    detalheLabel: {
        color: '#888',
        fontSize: 14,
    },
    detalheValor: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    estoqueAlerta: {
        color: '#F87171',
    },
    cancelButton: {
        color: '#3B82F6',
        fontSize: 16,
    },
    modalContent: {
        flex: 1,
        padding: 20,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputRow: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    inputLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#000',
        color: '#fff',
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
        fontSize: 16,
    },
    saveButton: {
        backgroundColor: '#9f795c',
        padding: 15,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 20,
    },
    saveButtonText: {
        color: '#e6e6e6',
        fontSize: 16,
        fontWeight: 'bold',
    },
    detalhesButton: {
        backgroundColor: '#333',
        borderRadius: 20,
        padding: 8,
    },
    fecharButton: {
        backgroundColor: '#F87171',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    fecharButtonText: {
        color: '#fff',
        fontWeight: '600',
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    openCaixaCard: {
        backgroundColor: '#1a1a1a',
        borderRadius: 20,
        padding: 30,
        width: '100%',
        maxWidth: 300,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    openCaixaTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        marginTop: 15,
        marginBottom: 10,
    },
    openCaixaSubtitle: {
        fontSize: 14,
        color: '#888',
        textAlign: 'center',
        marginBottom: 25,
    },
    valorInput: {
        backgroundColor: '#333',
        color: '#fff',
        padding: 15,
        borderRadius: 8,
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 20,
        width: '100%',
    },
    openButton: {
        backgroundColor: '#9f795c',
        padding: 15,
        borderRadius: 8,
        width: '100%',
        alignItems: 'center',
    },
    openButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    resumoContainer: {
        padding: 15,
    },
    resumoCard: {
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        padding: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    resumoLabel: {
        fontSize: 14,
        color: '#888',
        marginBottom: 5,
    },
    resumoValor: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#9f795c',
    },
    actionsContainer: {
        flexDirection: 'row',
        padding: 15,
        gap: 10,
    },
    actionCaixaButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 15,
        borderRadius: 12,
        gap: 8,
    },
    entradaButton: {
        backgroundColor: '#10B981',
    },
    saidaButton: {
        backgroundColor: '#F87171',
    },
    actionButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    movimentosList: {
        flex: 1,
        padding: 15,
    },
    movimentoCard: {
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        padding: 15,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#333',
    },
    movimentoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    tipoIndicator: {
        borderRadius: 20,
        padding: 6,
    },
    tipoEntrada: {
        backgroundColor: '#10B981',
    },
    tipoSaida: {
        backgroundColor: '#F87171',
    },
    movimentoInfo: {
        flex: 1,
    },
    movimentoDescricao: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    movimentoCategoria: {
        color: '#888',
        fontSize: 12,
    },
    movimentoValor: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    valorPositivo: {
        color: '#10B981',
    },
    valorNegativo: {
        color: '#F87171',
    },
    categoriaButtons: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    categoriaButton: {
        backgroundColor: '#333',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 16,
    },
    categoriaButtonActive: {
        backgroundColor: '#9f795c',
    },
    categoriaButtonText: {
        color: '#888',
        fontSize: 14,
    },
    categoriaButtonTextActive: {
        color: '#fff',
    },
    fechamentoInfo: {
        backgroundColor: '#1a1a1a',
        padding: 15,
        borderRadius: 8,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#333',
    },
    fechamentoLabel: {
        color: '#888',
        fontSize: 14,
        marginBottom: 5,
    },
    fechamentoValor: {
        color: '#9f795c',
        fontSize: 24,
        fontWeight: 'bold',
    },
    detalheItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // paddingVertical: 12,
        // borderBottomWidth: 1,
        // borderBottomColor: '#333',
    },
    detalheLabel: {
        color: '#888',
        fontSize: 14,
    },
    detalheValor: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    statusAberto: {
        color: '#10B981',
    },
    statusFechado: {
        color: '#888',
    },
    controls: {
        padding: 15,
        backgroundColor: '#1a1a1a',
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    tipoButtons: {
        flexDirection: 'row',
        marginBottom: 15,
        gap: 10,
    },
    tipoButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        backgroundColor: '#333',
        borderRadius: 8,
        gap: 8,
    },
    tipoButtonActive: {
        backgroundColor: '#9f795c',
    },
    tipoButtonText: {
        color: '#888',
        fontWeight: '600',
    },
    tipoButtonTextActive: {
        color: '#fff',
    },
    dateControls: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 15,
    },
    dateButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#333',
        borderRadius: 8,
        gap: 8,
    },
    dateButtonText: {
        color: '#fff',
        fontSize: 14,
    },
    generateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#9f795c',
        padding: 15,
        borderRadius: 8,
        gap: 8,
    },
    generateButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    resumoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 20,
    },
    resumoRelatorioCard: {
        flex: 1,
        minWidth: '45%',
        backgroundColor: '#1a1a1a',
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    resumoRelatorioValor: {
        fontSize: 24,
    },
    section: {
        marginBottom: 25,
    },
    movimentacaoItem: {
        backgroundColor: '#1a1a1a',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    movimentacaoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    movimentacaoData: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    movimentacaoValor: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    movimentacaoDescricao: {
        color: '#888',
        fontSize: 12,
    },
    vendaItem: {
        backgroundColor: '#1a1a1a',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    vendaHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    vendaPedido: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    vendaTotal: {
        color: '#10B981',
        fontSize: 14,
        fontWeight: 'bold',
    },
    vendaDetalhes: {
        color: '#888',
        fontSize: 12,
    },
    avaliacoesResumo: {
        flexDirection: 'row',
        gap: 15,
        marginBottom: 15,
    },
    avaliacaoItem: {
        flex: 1,
        backgroundColor: '#1a1a1a',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    avaliacaoLabel: {
        color: '#888',
        fontSize: 12,
        marginBottom: 5,
    },
    avaliacaoValor: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    avaliacoesPorCategoria: {
        backgroundColor: '#1a1a1a',
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    categoriaTitle: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 10,
    },
    categoriaItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 5,
    },
    categoriaLabel: {
        color: '#888',
        fontSize: 14,
        textTransform: 'capitalize',
    },
    categoriaValor: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    usuarioCard: {
        backgroundColor: '#1a1a1a',
        padding: 15,
        borderRadius: 8,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#333',
    },
    usuarioNome: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    usuarioEmail: {
        color: '#888',
        fontSize: 14,
        marginBottom: 10,
    },
    usuarioStats: {
        gap: 8,
        marginBottom: 10,
    },
    statItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statLabel: {
        color: '#888',
        fontSize: 14,
    },
    statValor: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    usuarioUltimoAcesso: {
        color: '#666',
        fontSize: 12,
        fontStyle: 'italic',
    },
    sectionSubtitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 10,
    },
    mediaGeralCard: {
        backgroundColor: '#000',
        padding: 20,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#6b4324',
        alignItems: 'center',
        marginBottom: 15,
    },
    mediaGeralLabel: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        marginBottom: 10,
    },
    mediaGeralInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
        marginBottom: 5,
    },
    mediaGeralValorGrande: {
        color: '#6b4324',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
    },
    mediaGeralStars: {
        flexDirection: 'row',
        gap: 3,
    },
    totalAvaliacoes: {
        color: '#9f795c',
        fontSize: 12,
        fontFamily: 'Inter-Regular',
    },
    mediasPorCategoria: {
        gap: 8,
    },
    categoriaResumo: {
        backgroundColor: '#000',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    categoriaResumoNome: {
        color: '#e6e6e6',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
    },
    categoriaResumoValor: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: '10px',
        gap: 8,
    },
    mediaValor: {
        color: '#6b4324',
        fontSize: 16,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        minWidth: 30,
        textAlign: 'right',
    },
    avaliacoesList: {
        flex: 1,
        paddingHorizontal: 15,
    },
    avaliacaoCard: {
        backgroundColor: '#000',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    avaliacaoPageCard: {
        backgroundColor: '#000',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    avaliacaoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    avaliacaoPageHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    avaliacaoData: {
        flex: 1,
    },
    avaliacaoPageData: {
        flex: 1,
    },
    dataText: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
    },
    nomeText: {
        color: '#e6e6e6',
        fontSize: 12,
        marginTop: 2,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
    },
    mediaGeral: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    mediaGeralValor: {
        color: '#6b4324',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
    },
    starsContainer: {
        flexDirection: 'row',
        gap: 1,
    },
    categoriasGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 15,
    },
    categoriaAvaliacaoItem: {
        flex: 1,
        minWidth: '45%',
        backgroundColor: '#000',
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    categoriaAvaliacaoLabel: {
        color: '#9f795c',
        fontSize: 12,
        fontFamily: 'Inter-Regular',
        marginBottom: 5,
    },
    categoriaAvaliacaoValor: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    categoriaNumero: {
        color: '#e6e6e6',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Inter-SemiBold',
        minWidth: 25,
    },
    comentarioContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        backgroundColor: '#000',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#6b4324',
    },
    comentarioTexto: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        flex: 1,
        lineHeight: 20,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
    },
    emptyStateTitle: {
        color: '#e6e6e6',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Inter-Bold',
        marginTop: 15,
        marginBottom: 8,
    },
    emptyStateText: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
        textAlign: 'center',
        lineHeight: 20,
    },
    loadingMore: {
        padding: 20,
        alignItems: 'center',
    },
    loadingMoreText: {
        color: '#9f795c',
        fontSize: 14,
        fontFamily: 'Inter-Regular',
    },
    logoutButton: {
        backgroundColor: '#F87171',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
    },
    logoutButtonText: {
        color: '#fff',
        fontWeight: '600',
    },
    accessDenied: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    accessDeniedTitle: {
        color: '#F87171',
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 15,
        marginBottom: 10,
    },
    accessDeniedText: {
        color: '#888',
        fontSize: 16,
        textAlign: 'center',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 5,
    },
    usuarioAdminCard: {
        backgroundColor: '#1a1a1a',
        borderRadius: 8,
        padding: 15,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#333',
        flexDirection: 'row',
        alignItems: 'center',
    },
    usuarioAdminInfo: {
        flex: 1,
    },
    usuarioAdminNome: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    usuarioAdminEmail: {
        color: '#888',
        fontSize: 14,
        marginBottom: 2,
    },
    usuarioAdminRole: {
        color: '#3B82F6',
        fontSize: 12,
        textTransform: 'capitalize',
    },
    usuarioAdminActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    dataActions: {
        gap: 10,
    },
    dataButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#9f795c',
        padding: 15,
        borderRadius: 8,
        gap: 8,
    },
    dangerButton: {
        backgroundColor: '#F87171',
    },
    dataButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    systemInfo: {
        backgroundColor: '#1a1a1a',
        borderRadius: 8,
        padding: 15,
        borderWidth: 1,
        borderColor: '#333',
    },
    infoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    infoLabel: {
        color: '#888',
        fontSize: 14,
    },
    infoValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    inputDisabled: {
        backgroundColor: '#333',
        color: '#888',
    },
    roleButtons: {
        gap: 8,
    },
    roleButton: {
        backgroundColor: '#333',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    roleButtonActive: {
        backgroundColor: '#9f795c',
    },
    roleButtonText: {
        color: '#888',
        fontSize: 14,
        fontWeight: '600',
    },
    roleButtonTextActive: {
        color: '#fff',
    },
});

export { styles }; // or export default styles;